<a href="https://colab.research.google.com/github/Zhigurt/Python-for-Data-Science-Numpy-Matplotlib-Scikit-learn/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22Lesson1_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Тема “Вычисления с помощью Numpy”

# Задание 1


Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [ ]:
import numpy as np


Вводим первый набор данных

In [ ]:
x = np.array([1,2,3,3,1])

In [ ]:
print(x)

[1 2 3 3 1]


Вводим второй набор данных

In [ ]:
y = np.array([6, 8, 11, 10, 7])

In [ ]:
print(y)

[ 6  8 11 10  7]


Создадим матрицу z состоящую из двух наборов значений

In [ ]:
z = np.vstack((x, y)) 
print(z)

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]


Создадим матрицу а Транспонируя матрицу z для условий задания 

In [ ]:
a = z.T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

Найдем средние значения каждого из признаков и создадим матрицу из полученных значений

In [ ]:
mean_a = a.mean(axis=0)
mean_a


array([2. , 8.4])

# Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [ ]:
a_certered = np.subtract(a, mean_a)
a_certered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

# Задание 3


Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [ ]:
rshape1 = a_certered[[0,1,2,3,4], 0 ]
rshape2 = a_certered[[0,1,2,3,4], 1 ]
a_centered_sp = rshape1 @ rshape2
a_centered_sp 

8.0

In [ ]:
N = len(a[:,1])
print(N)

5


In [ ]:
covariant = a_centered_sp / (N-1)
print(covariant)

2.0


# Задание 4

In [ ]:
N = np.cov(a.T)
print(N)

[[1.  2. ]
 [2.  4.3]]


# Тема “Работа с данными в Pandas”

# Задание 1


Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].


In [ ]:
import pandas as pd
author_id = [1, 2, 3]
author_name = ['Тургенев', 'Чехов', 'Островский']
author = pd.Series(author_name)            
print(author)


0      Тургенев
1         Чехов
2    Островский
dtype: object


In [ ]:
autor = pd.DataFrame({
    'autor_id' : [1, 2, 3],
    'autor_name' : ['Тургенев', 'Чехов', 'Островский'],
})
autor

autor_id  autor_name
0         1    Тургенев
1         2       Чехов
2         3  Островский

In [ ]:

book = pd.DataFrame({
    'autor_id' : [1, 1, 1, 2, 2, 3, 3],
    'book_title' : ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price' : [450, 300, 350, 500, 450, 370, 290],
})
book

autor_id            book_title  price
0         1           Отцы и дети    450
1         1                 Рудин    300
2         1     Дворянское гнездо    350
3         2      Толстый и тонкий    500
4         2       Дама с собачкой    450
5         3                 Гроза    370
6         3  Таланты и поклонники    290

# Задание 2 

Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [ ]:

autors_price = pd.merge(autor, book, on='autor_id', how='outer')
autors_price




autor_id  autor_name            book_title  price
0         1    Тургенев           Отцы и дети    450
1         1    Тургенев                 Рудин    300
2         1    Тургенев     Дворянское гнездо    350
3         2       Чехов      Толстый и тонкий    500
4         2       Чехов       Дама с собачкой    450
5         3  Островский                 Гроза    370
6         3  Островский  Таланты и поклонники    290

# Задание 3 

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [ ]:
top5 = autors_price.nlargest(5, "price")
top5

autor_id  autor_name         book_title  price
3         2       Чехов   Толстый и тонкий    500
0         1    Тургенев        Отцы и дети    450
4         2       Чехов    Дама с собачкой    450
5         3  Островский              Гроза    370
2         1    Тургенев  Дворянское гнездо    350

# Задание 4 

Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.


In [ ]:
stat = autors_price.groupby("autor_name")
max_price = stat.agg({"price": "max", "price": "mean", "price": "min" })
max_price = max_price.reset_index()
max_price = max_price.rename(columns = {'price' : 'max_price','price' : 'mean_price', 'price' : 'mean_price'}) 
max_price






autor_name  mean_price
0  Островский         290
1    Тургенев         300
2       Чехов         450

In [ ]:

mean_price = stat.agg({"price": "mean"})
mean_price = mean_price.reset_index()
mean_price = mean_price.rename(columns = {'price' : 'mean_price'}) 

min_price = stat.agg({"price": "min"})
min_price = min_price.reset_index()
min_price = min_price.rename(columns = {'price' : 'min_price'}) 